import os
import uuid
from contextlib import asynccontextmanager
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from motor.motor_asyncio import AsyncIOMotorClient
from sentence_transformers import SentenceTransformer
from dotenv import load_dotenv

load_dotenv()

db = None
callers_collection = None
books_collection = None
reservations_collection = None
embedding_model = None

@asynccontextmanager
async def lifespan(app: FastAPI):
    global db, callers_collection, books_collection, reservations_collection, embedding_model

    print("Loading embedding model...")
    embedding_model = SentenceTransformer('all-MiniLM-L6-v2')
    print("✅ Embedding model loaded!")

    print("Connecting to MongoDB Atlas...")
    mongo_client = AsyncIOMotorClient(os.getenv("MONGO_URI"))
    db = mongo_client["library_db"]
    callers_collection = db["callers"]
    books_collection = db["books"]
    reservations_collection = db["reservations"]
    print("✅ Connected to MongoDB Atlas!")

    yield

    print("Closing MongoDB connection...")
    mongo_client.close()

app = FastAPI(lifespan=lifespan)


# ── 1. VERIFY CALLER ─────────────────────────────────
@app.get("/callers/{phone}")
async def verify_caller(phone: str):
    caller = await callers_collection.find_one({"phone": phone})
    if not caller:
        raise HTTPException(status_code=404, detail="Caller not found")
    caller["_id"] = str(caller["_id"])
    return caller


# ── 2. UNIFIED SEMANTIC VECTOR SEARCH ────────────────
@app.get("/books")
async def search_books(q: str):
    # If the agent passes an empty string, return an empty set immediately
    if not q.strip():
        return {"results": []}

    # Turn the conversational text query into an array of 384 coordinates
    query_vector = embedding_model.encode(q).tolist()
    
    # Execute the Atlas Vector Search pipeline stage
    pipeline = [
        {
            "$vectorSearch": {
                "index": "vector_index",      # Must match the index name created in Atlas UI
                "path": "embedding",         # Target coordinate array field in your documents
                "queryVector": query_vector,  # The float array generated by SentenceTransformer
                "numCandidates": 20,
                "limit": 5
            }
        },
        {
            "$project": {
                "_id": 0,                    # The ONLY exclusion allowed alongside inclusions!
                "id": 1,                     # Explicitly include the custom book ID string
                "title": 1,                  # Explicitly include the title
                "available": 1,              # Explicitly include availability status
                "description": 1,            # Explicitly include the text description
                "score": {"$meta": "vectorSearchScore"} # Include match score calculation
            }
        }
    ]
    
    results = await books_collection.aggregate(pipeline).to_list(length=5)
    return {"results": results}


# ── 3. MAKE RESERVATION ──────────────────────────────
class ReservationRequest(BaseModel):
    caller_phone: str
    book_id: str
    pickup_date: str

@app.post("/reservations")
async def make_reservation(req: ReservationRequest):
    book = await books_collection.find_one({"id": req.book_id})
    if not book:
        raise HTTPException(status_code=404, detail="Book not found")
    if not book.get("available", True):
        raise HTTPException(status_code=400, detail="Book not available")

    reservation_id = "R" + str(uuid.uuid4())[:3].upper()
    new_reservation = {
        "id": reservation_id,
        "caller_phone": req.caller_phone,
        "book_id": req.book_id,
        "book_title": book["title"],
        "pickup_date": req.pickup_date,
        "status": "active"
    }

    await books_collection.update_one({"id": req.book_id}, {"$set": {"available": False}})
    await reservations_collection.insert_one(new_reservation)
    new_reservation["_id"] = str(new_reservation["_id"])
    return {"message": "Reservation created", "reservation": new_reservation}


# ── 4. UPDATE RESERVATION ────────────────────────────
class UpdateRequest(BaseModel):
    pickup_date: str

@app.patch("/reservations/{reservation_id}")
async def update_reservation(reservation_id: str, req: UpdateRequest):
    reservation = await reservations_collection.find_one({"id": reservation_id})
    if not reservation:
        raise HTTPException(status_code=404, detail="Reservation not found")

    await reservations_collection.update_one(
        {"id": reservation_id},
        {"$set": {"pickup_date": req.pickup_date}}
    )
    reservation["pickup_date"] = req.pickup_date
    reservation["_id"] = str(reservation["_id"])
    return {"message": "Reservation updated", "reservation": reservation}


# ── 5. CANCEL RESERVATION ────────────────────────────
@app.delete("/reservations/{reservation_id}")
async def cancel_reservation(reservation_id: str):
    reservation = await reservations_collection.find_one({"id": reservation_id})
    if not reservation:
        raise HTTPException(status_code=404, detail="Reservation not found")

    await reservations_collection.delete_one({"id": reservation_id})
    await books_collection.update_one(
        {"id": reservation["book_id"]},
        {"$set": {"available": True}}
    )
    return {"message": "Reservation cancelled", "book": reservation["book_title"]}


# ── 6. GET RESERVATIONS BY PHONE ─────────────────────
@app.get("/reservations")
async def get_reservations_by_phone(phone: str):
    cursor = reservations_collection.find({"caller_phone": phone})
    reservations = await cursor.to_list(length=20)
    if not reservations:
        return {"reservations": [], "message": "No active reservations found."}
    for r in reservations:
        r["_id"] = str(r["_id"])
    return {"reservations": reservations}